"""initial

Revision ID: 11302f28443a
Revises: 
Create Date: 2023-08-13 09:19:11.260882

"""
from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "11302f28443a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
